ticker_name: "^GSPC"
start_date: "2000-01-01"
target_num: 1

features:
  - 'RSI'
  - 'MFI'
  - 'ADX'
  - 'Z_Score_10'
  - 'Volatility'
  - 'Dist_SMA_10'
  - 'Dist_SMA_50'
  - 'Dist_SMA_200'
  - 'Log_Volume'
  - 'Log_Vol_Change'
  - 'Trend_Signal'
  - 'Ret_L1'
  - 'Ret_L2'
  - 'VIX'
  - 'VIX_Change'
  - 'Fed_Rate'
  - 'Unemployment'
  - 'Inflation_var'
  - 'stress_fed'
  - 'yield_10y'
  - 'yield_2y'
  - 'Yield_Spread'
  - 'Yield_Spread_Change'

# Paramètres globaux de trading
horizon: 1
frais: 0

# Les seuils de trading que tu veux tester dans le GridSearch
trading_configs:
  - {seuil_achat: 0.501, seuil_short: 0.499}
  - {seuil_achat: 0.550, seuil_short: 0.450}
  - {seuil_achat: 0.5, seuil_short: 0.4}
  - { seuil_achat: 0.6, seuil_short: 0.3 }
  - { seuil_achat: 0.5, seuil_short: 0.3 }
