ticker_name: "^GSPC"
start_date: "1995-01-01"
model_type: "classification"

#features:
#  - 'RSI'
#  - 'ADX'
#  - 'Volatility'
#  - 'Dist_SMA_200'
#  - 'Ret_L1'
#  - 'VIX_Change'
#  - 'Fed_Rate'
#  - 'Inflation_var'
#  - 'stress_fed'
#  - 'Yield_Spread'
#  - 'Yield_Spread_Change'

# Paramètres globaux de trading
horizon: 20
frais: 0

features:
  - 'RSI'
  - 'ADX'
  - 'Z_Score_10'
  - 'Volatility'
  - 'Dist_SMA_10'
  - 'Dist_SMA_200'
  - 'Log_Vol_Change'
  - 'Trend_Signal'
  - 'Ret_L1'
  - 'Ret_L2'
  - 'VIX_Change'
  - 'Fed_Rate'
  - 'Inflation_var'
  - 'stress_fed'
  - 'Yield_Spread'
  - 'Yield_Spread_Change'